GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FlashoramaiOS10
FlashoramaiOS10_FILES = Tweak.xm
FlashoramaiOS10_LIBRARIES = substrate
FlashoramaiOS10_INSTALL_PATH = /Library/Application Support/Flashorama

include $(THEOS_MAKE_PATH)/library.mk
