TARGET = iphone:8.1:8.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FlashoramaiOS8
FlashoramaiOS8_FILES = Tweak.xm
FlashoramaiOS8_FRAMEWORKS = AVFoundation
FlashoramaiOS8_EXTRA_FRAMEWORKS = CydiaSubstrate
FlashoramaiOS8_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries/Flashorama

include $(THEOS_MAKE_PATH)/library.mk
