GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FlashoramaiOS8
FlashoramaiOS8_FILES = Tweak.xm
FlashoramaiOS8_FRAMEWORKS = AVFoundation
FlashoramaiOS8_LIBRARIES = substrate
FlashoramaiOS8_INSTALL_PATH = /Library/Application Support/Flashorama

include $(THEOS_MAKE_PATH)/library.mk
