TARGET = iphone:6.1:6.0
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FlashoramaiOS6
FlashoramaiOS6_FILES = Tweak.xm
FlashoramaiOS6_FRAMEWORKS = AVFoundation
FlashoramaiOS6_EXTRA_FRAMEWORKS = CydiaSubstrate
FlashoramaiOS6_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries/Flashorama

include $(THEOS_MAKE_PATH)/library.mk
