GO_EASY_ON_ME = 1
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FlashoramaiOS6
FlashoramaiOS6_FILES = Tweak.xm
FlashoramaiOS6_FRAMEWORKS = AVFoundation
FlashoramaiOS6_LIBRARIES = substrate
FlashoramaiOS6_INSTALL_PATH = /Library/Application Support/Flashorama

include $(THEOS_MAKE_PATH)/library.mk
