TARGET = iphone:11.2:10.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FlashoramaiOSAB
FlashoramaiOSAB_FILES = Tweak.xm
FlashoramaiOSAB_EXTRA_FRAMEWORKS = CydiaSubstrate
FlashoramaiOSAB_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries/Flashorama

include $(THEOS_MAKE_PATH)/library.mk
