TARGET = iphone:9.2:9.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FlashoramaiOS9
FlashoramaiOS9_FILES = Tweak.xm
FlashoramaiOS9_EXTRA_FRAMEWORKS = CydiaSubstrate
FlashoramaiOS9_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries/Flashorama

include $(THEOS_MAKE_PATH)/library.mk
