GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FlashoramaiOS9
FlashoramaiOS9_FILES = Tweak.xm
FlashoramaiOS9_LIBRARIES = substrate
FlashoramaiOS9_INSTALL_PATH = /Library/Application Support/Flashorama

include $(THEOS_MAKE_PATH)/library.mk
