GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FlashoramaiOS7
FlashoramaiOS7_FILES = Tweak.xm
FlashoramaiOS7_FRAMEWORKS = AVFoundation
FlashoramaiOS7_LIBRARIES = substrate
FlashoramaiOS7_INSTALL_PATH = /Library/Application Support/Flashorama

include $(THEOS_MAKE_PATH)/library.mk
