TARGET = iphone:7.1:7.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FlashoramaiOS7
FlashoramaiOS7_FILES = Tweak.xm
FlashoramaiOS7_FRAMEWORKS = AVFoundation
FlashoramaiOS7_EXTRA_FRAMEWORKS = CydiaSubstrate
FlashoramaiOS7_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries/Flashorama

include $(THEOS_MAKE_PATH)/library.mk
